### ISSUE TITLE
support export/import of data structure

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [spenczar/tdigest#2]
due to the centroid implementation of the `TDigest` interface being private, it is currently not possible to get at the fields easily.

the use case I have in mind is creating and populating `centroidSet` on various separate machines, serializing them, sending them across the network to an aggregator machine, and then on this aggregator, deserializing and merging them.

**Comment by spenczar** [comment]
That's a reasonable feature request. We could implement the same scheme as the reference implementation, https://github.com/tdunning/t-digest/blob/master/core/src/main/java/com/tdunning/math/stats/MergingDigest.java#L778-L790.
