### ISSUE TITLE
unmarshalling fails for values {1, 1, 0}

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [spenczar/tdigest#6]
I came across a failure to unmarshal via `UnmarshalBinary` of a value that was previously marshaled. I was able to simplify my test case to a t-digest containing the values {1, 1, 0}.

The test program is:

```
package main

import (
	"fmt"

	"github.com/spenczar/tdigest"
)

var vals []float64 = []float64{1, 1, 0}

func main() {
	t := tdigest.New()
	for _, val := range vals {
		t.Add(val, 1)
	}

	b, err := t.MarshalBinary()
	if err != nil {
		panic(err)
	}

	t2 := tdigest.New()
	err = t2.UnmarshalBinary(b)
	if err != nil {
		panic(err)
	}

	fmt.Println(t2.Quantile(1))
}
```

The error it returned is:

```
data corruption detected: centroid 1 has lower mean (0.5) than preceding centroid 0 (1)
```

Fuzzing would likely uncover similar cases. Hopefully the reproduce case is small enough to allow you to debug what's going on.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
For the record, this is running on the new `v2.0.0` tag.

**Comment by spenczar** [comment]
Thanks for the report. This looks like it's a bug in the `Add` logic, not marshaling/unmarshaling. I'll dig in.

**Comment by igorwwwwwwwwwwwwwwwwwwww** [comment]
Thank you for the fast fix, yet again! ❤️
